version: '2'
services:
  searx:
    build: .
    image: adeweever91/searx_ss:latest
    environment:
      BASE_URL: https://searx.example.com
      IMAGE_PROXY: 'True'
    ports:
    - 80:80/tcp
    - 443:443/tcp
